name = "act"
version = "0.3.0"
description = "Compose stateful actions to simulate mutable state"
licences = ["Apache-2.0"]
repository = { type = "github", user = "MystPi", repo = "act" }

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
